server:
  port: 9000

spring:
  application:
    name: demo

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: rhfms2clrhk
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      format_sql: true


